-- Create offers table
CREATE TABLE IF NOT EXISTS public.offers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    coupon_code text NOT NULL,
    discount_percentage integer NOT NULL,
    heading text NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    is_active boolean DEFAULT true
);

-- Basic RLS
ALTER TABLE public.offers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON public.offers
    FOR SELECT USING (true);

-- Seed Data
INSERT INTO public.offers (coupon_code, discount_percentage, heading, start_date, end_date, is_active)
VALUES 
(
    'CHEESE1218', 
    30, 
    '🎉 Get 30% OFF with code CHEESE1218! Valid Jan 12 - Jan 18.', 
    '2026-01-12', 
    '2026-01-18', 
    true
)
ON CONFLICT DO NOTHING;
